name:                wordle-solver
version:             0.1.0.0
github:              sgillespie/wordle-solver
license:             BSD3
author:              Sean Gillespie
maintainer:          sean@mistersg.net
copyright:           2022 Sean Gillespie

extra-source-files:
  - README.md

description: Please see the README on Github at <https://github.com/githubuser/wordle-solver#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src

executables:
  wordle-solver-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - wordle-solver
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  wordle-solver-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - wordle-solver
      - hspec

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
